#!/usr/bin/env python3
"""
Auto-generates all audio plumbing for custom music tracks.

Drop an MP3 into assets/audio/samples/CustomMusic/ and run make.
This script generates:
  - assets/audio/samplebanks/CustomMusic.xml
  - assets/audio/soundfonts/CustomSoundfont.xml
  - assets/audio/sequences/seq_custom_<name>.seq  (one per MP3)
  - include/tables/custom_sequence_table.h

It also maintains the BEGIN_CUSTOM/END_CUSTOM marker sections in spec/spec.
"""

import os
import re

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

CUSTOM_MUSIC_DIR = os.path.join(REPO_ROOT, "assets/audio/samples/CustomMusic")
SAMPLEBANK_DIR   = os.path.join(REPO_ROOT, "assets/audio/samplebanks")
SOUNDFONT_DIR    = os.path.join(REPO_ROOT, "assets/audio/soundfonts")
SEQUENCE_DIR     = os.path.join(REPO_ROOT, "assets/audio/sequences")
TABLES_DIR       = os.path.join(REPO_ROOT, "include/tables")
SPEC_FILE        = os.path.join(REPO_ROOT, "spec/spec")

SAMPLEBANK_NAME  = "CustomMusic"
SAMPLEBANK_INDEX = 7
SOUNDFONT_NAME   = "CustomSoundfont"
SOUNDFONT_INDEX  = 38


def discover_mp3s():
    if not os.path.isdir(CUSTOM_MUSIC_DIR):
        return []
    entries = []
    for fname in sorted(os.listdir(CUSTOM_MUSIC_DIR)):
        if fname.lower().endswith(".mp3"):
            entries.append(os.path.splitext(fname)[0])
    return entries


def gen_samplebank_xml(names):
    lines = [
        f'<SampleBank Name="{SAMPLEBANK_NAME}" Index="{SAMPLEBANK_INDEX}"'
        f' Medium="MEDIUM_CART" CachePolicy="CACHE_LOAD_EITHER_NOSYNC">',
    ]
    for name in names:
        aifc = f"$(BUILD_DIR)/assets/audio/samples/CustomMusic/{name}.aifc"
        lines.append(f'    <Sample Name="CUSTOM_{name}" Path="{aifc}"/>')
    lines.append("</SampleBank>")
    return "\n".join(lines) + "\n"


def gen_soundfont_xml(names):
    sb = f"$(BUILD_DIR)/assets/audio/samplebanks/{SAMPLEBANK_NAME}.xml"
    lines = [
        f'<Soundfont Name="{SOUNDFONT_NAME}" Index="{SOUNDFONT_INDEX}"',
        f'           Medium="MEDIUM_CART" CachePolicy="CACHE_LOAD_TEMPORARY"',
        f'           SampleBank="{sb}">',
        "    <Envelopes>",
        '        <Envelope Name="Env_hold" Release="127">',
        '            <Point Delay="1" Arg="32700"/>',
        '            <Point Delay="32700" Arg="32700"/>',
        "        </Envelope>",
        "    </Envelopes>",
        "    <Samples>",
    ]
    for name in names:
        lines.append(f'        <Sample Name="CUSTOM_{name}"/>')
    lines.append("    </Samples>")
    lines.append("    <Instruments>")
    for idx, name in enumerate(names):
        lines.append(
            f'        <Instrument ProgramNumber="{idx}" Name="INST_{name}"'
            f' Envelope="Env_hold" Sample="CUSTOM_{name}"/>'
        )
    lines.append("    </Instruments>")
    lines.append("</Soundfont>")
    return "\n".join(lines) + "\n"


def gen_sequence(name, instr_idx):
    up = name.upper()
    return f"""\
#include "aseq.h"
#include "{SOUNDFONT_NAME}.h"

.startseq Sequence_custom_{name}

.sequence SEQ_START
    mutebhv     0x20
    mutescale   70
    vol         255
    tempo       120
    initchan    0b0000000000000001
    ldchan      0, CHAN_MUSIC
SEQ_HOLD:
    delay       0x7FFF
    jump        SEQ_HOLD

.channel CHAN_MUSIC
    vol         127
    pan         64
    font        0
    instr       {instr_idx}
    noshort
    ldlayer     0, LAYER_MUSIC
CHAN_HOLD:
    delay       0x7FFF
    jump        CHAN_HOLD

.layer LAYER_MUSIC
LAYER_LOOP:
    notedv      39, 0x7FFF, 127
    jump        LAYER_LOOP

.endseq Sequence_custom_{name}
"""


def gen_sequence_table(names):
    if not names:
        return "/* No custom music — add MP3s to assets/audio/samples/CustomMusic/ */\n"
    lines = ["/* Auto-generated by tools/audio/gen_custom_audio.py — do not edit manually */"]
    for idx, name in enumerate(names):
        seq  = f"Sequence_custom_{name}"
        bgm  = f"NA_BGM_CUSTOM_{name.upper()}"
        lines.append(
            f"DEFINE_SEQUENCE    ({seq},{' ' * (32 - len(seq))}"
            f" {bgm},{' ' * (30 - len(bgm))}"
            f" MEDIUM_CART, CACHE_LOAD_TEMPORARY,  0) // {name}.mp3"
        )
    return "\n".join(lines) + "\n"


def update_spec(names):
    with open(SPEC_FILE) as f:
        content = f.read()

    sections = {
        "AUDIOBANK": [
            f'    include "$(BUILD_DIR)/assets/audio/soundfonts/{SOUNDFONT_NAME}.o"',
        ],
        "AUDIOTABLE": [
            f'    include "$(BUILD_DIR)/assets/audio/samplebanks/{SAMPLEBANK_NAME}.o"',
        ],
        "AUDIOSEQ": [
            f'    include "$(BUILD_DIR)/assets/audio/sequences/seq_custom_{n}.o"'
            for n in names
        ],
    }

    for tag, new_lines in sections.items():
        begin = f"    /* BEGIN_CUSTOM_{tag} */"
        end   = f"    /* END_CUSTOM_{tag} */"
        inner = ("\n".join(new_lines) + "\n") if new_lines else ""
        pattern = rf"({re.escape(begin)}\n).*?({re.escape(end)})"
        content = re.sub(pattern, rf"\g<1>{inner}\2", content, flags=re.DOTALL)

    with open(SPEC_FILE, "w") as f:
        f.write(content)


def write_if_changed(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    try:
        with open(path) as f:
            if f.read() == content:
                return
    except FileNotFoundError:
        pass
    with open(path, "w") as f:
        f.write(content)
    print(f"  Updated: {os.path.relpath(path, REPO_ROOT)}")


def main():
    names = discover_mp3s()
    print(f"Custom music: {names if names else '(none)'}")

    write_if_changed(os.path.join(SAMPLEBANK_DIR, f"{SAMPLEBANK_NAME}.xml"),
                     gen_samplebank_xml(names))
    write_if_changed(os.path.join(SOUNDFONT_DIR, f"{SOUNDFONT_NAME}.xml"),
                     gen_soundfont_xml(names))

    for idx, name in enumerate(names):
        write_if_changed(
            os.path.join(SEQUENCE_DIR, f"seq_custom_{name}.seq"),
            gen_sequence(name, idx),
        )

    active = {f"seq_custom_{n}.seq" for n in names}
    for f in os.listdir(SEQUENCE_DIR):
        if f.startswith("seq_custom_") and f.endswith(".seq") and f not in active:
            os.remove(os.path.join(SEQUENCE_DIR, f))
            print(f"  Removed: {os.path.relpath(os.path.join(SEQUENCE_DIR, f), REPO_ROOT)}")

    write_if_changed(os.path.join(TABLES_DIR, "custom_sequence_table.h"),
                     gen_sequence_table(names))

    update_spec(names)
    print("Custom audio generation complete.")


if __name__ == "__main__":
    main()
